camel:
  springboot:
    name: demo-kafka-producer
  servlet:
    mapping:
      context-path: /demo-kafka-producer/*

management:
  endpoints:
    web:
      exposure:
        include: health, loggers, prometheus

spring:
  mvc:
    static-path-pattern: /demo-kafka-producer/static/**

  web:
    resources:
      add-mappings: true
      static-locations:
        - classpath:/demo-kafka-producer/static/

dev:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}   # Inject from GitHub Secrets
    jaas-user: ${KAFKA_USERNAME}
    jaas-password: ${KAFKA_PASSWORD}
    auto-offset-reset: latest
    max-poll-records: 500
    consumers-count: 1
    group-id: ${KAFKA_GROUP_ID}
    seek-to: end
    topics:
      if5: ${KAFKA_TOPIC}

    ## IMPORTANT
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl:
        mechanism: SCRAM-SHA-512
        jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username='${KAFKA_USERNAME}' password='${KAFKA_PASSWORD}';"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTION_PASSWORD}

server:
  max-http-header-size: 10000000

logging.config: classpath:logback-prd.xml
