# edited
name: Build and Push Docker Image

on:
  push:
    # paths:
    #   - "src/**"
    #   - "pom.xml"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image to ACR
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          ACR_IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/demo-kafka-producer

          docker build -t $ACR_IMAGE:$IMAGE_TAG .
          docker tag $ACR_IMAGE:$IMAGE_TAG $ACR_IMAGE:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker push $ACR_IMAGE:$IMAGE_TAG
          docker push $ACR_IMAGE:latest

      - name: Trigger Helm Deployment in `helm-repo`
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/<your-org>/helm-repo/actions/workflows/deploy-helm.yaml/dispatches \
               -d '{"ref": "main", "inputs": {"imageTag": "'${{ env.IMAGE_TAG }}'"}}'
