name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests -P production

      # Authenticate with Azure using OIDC (Correct Fix)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image to ACR
        env:
          DOCKER_BUILDKIT: 0  # Disable BuildKit
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          ACR_IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/demo-kafka-producer
          JAR_FILE="target/demo-kafka-producer-0.0.1-SNAPSHOT.jar"
          
          # Ensure the JAR file exists before Docker build
          ls -l target/
          
          # Build the Docker image with the correct JAR file path
          docker build --build-arg JAR_FILE=$JAR_FILE -t $ACR_IMAGE:$IMAGE_TAG .
          
          docker tag $ACR_IMAGE:$IMAGE_TAG $ACR_IMAGE:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
          docker push $ACR_IMAGE:$IMAGE_TAG
          docker push $ACR_IMAGE:latest

      - name: Trigger Helm Deployment in `helm-repo`
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.HELM_REPO_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ secrets.HELM_REPO_OWNER }}/actions/workflows/deploy.yaml/dispatches \
               -d '{"ref": "main", "inputs": {"imageTag": "'${{ env.IMAGE_TAG }}'"}}'

